/* starter data for the database (admin, user, animal info, pet profiles etc.) */
/* INSERT INTO commands */


/*ANIMAL CARE*/

INSERT INTO `animal` (`animalID`, `species`, `facts`, `characteristics`, `averageLifespan`, `forbiddenFood`, `imgUrl`, `pageUrl`) VALUES (NULL, 'Dog', 'The domestic dog (Canis familiaris or Canis lupus familiaris) is a domesticated form of wolf. The dog descended from an ancient, extinct wolf, with the modern grey wolf being the dogs nearest living relative. The dog was the first species to be domesticated by hunter–gatherers over 15,000 years ago, before the development of agriculture.', 'Dogs are known to be faithful and loyal companions, protective of their masters and territory. There are several breeds, each possessing its own characteristics.', '10–13 years', 'Alcohol, Apple Seeds, Avocado, Candy, Chewing Gum, Toothpaste & Mouthwash, Cat Food, Chocolate, Coffee, Tea, Cooked Bones, Corn On The Cob, Fat Trimmings, Garlic, Grapes & Raisins, Hops, Human Vitamins, Liver', 'animalcare-dog.jpeg', 'animalcare-dog.php');
INSERT INTO `animal` (`animalID`, `species`, `facts`, `characteristics`, `averageLifespan`, `forbiddenFood`, `imgUrl`, `pageUrl`) VALUES (NULL, 'Cat', 'The cat (Felis catus) is a domestic species of small carnivorous mammal. It is the only domesticated species in the family Felidae and is often referred to as the domestic cat to distinguish it from the wild members of the family. A cat can either be a house cat, a farm cat or a feral cat; the latter ranges freely and avoids human contact', 'Although every cat has its own personality, all cats have some characteristics that some people find endearing and others find off-putting. Cats can be inquisitive, friendly, playful, active, loving and independent.', '2–16 years', 'Onions and Garlic, Raw Eggs, Raw Meat & Bones, Chocolate, Caffeinated Drinks, Alcohol, Raw Dough, Milk and Dairy, Grapes and Raisins', 'animalcare-cat.jpeg', 'animalcare-cat.php');
INSERT INTO `animal` (`animalID`, `species`, `facts`, `characteristics`, `averageLifespan`, `forbiddenFood`, `imgUrl`, `pageUrl`) VALUES (NULL, 'Hamster', 'Hamsters are rodents (order Rodentia) belonging to the subfamily Cricetinae, which contains 19 species classified in seven genera. They have become established as popular small pets. The best-known species of hamster is the golden or Syrian hamster (Mesocricetus auratus), which is the type most commonly kept as pets.', 'Hamsters are solitary creatures that prefer to be alone. When adult male hamsters are kept together, they will become violent and attempt to kill each other. With humans, however, hamsters are usually friendly and docile. They react well to being handled and they rarely bite.', '2–3 years', 'Garlic, Onion, Parsley, Celery, Oregano, Basil, Radishes, Raw beans', 'animalcare-hamster.jpeg', 'animalcare-hamster.php');
